WebApplication-MVC-2024C2/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication_MVC_2024C2.Context;
using WebApplication_MVC_2024C2.Models;


namespace WebApplication_MVC_2024C2.Controllers
{
    public class VentasController : Controller
    {
        private readonly CineDataBaseContext _context;

        public VentasController(CineDataBaseContext context)
        {
            _context = context;
        }

        // GET: Ventas
        public async Task<IActionResult> Index()
        {
            var ventas = await _context.Ventas.ToListAsync();
            return View(ventas);
        }

        // GET: Ventas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // Aseguramos que el navbar esté oculto si estamos en la acción de creación
            ViewData["HideNavbar"] = true;
           
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (venta == null)
            {
                return NotFound();
            }

            // Obtener la película asociada a la venta usando el IdPelicula
            var pelicula = _context.Peliculas
                .FirstOrDefault(p => p.Id == venta.IdPelicula);

            // Pasar el título de la película al ViewData
            ViewData["PeliculaTitulo"] = pelicula?.Titulo;

            return View(venta);
        }

        // GET: Ventas/Create
        public async Task<IActionResult> Create(int? peliculaId)
        {

            // Indicar en la vista que el navbar no se debe mostrar
            ViewData["HideNavbar"] = true;

            // Establecer en TempData que el usuario ha iniciado sesión
            TempData["IsUserLoggedIn"] = true;

            // Obtener las películas desde la base de datos
            var peliculas = await _context.Peliculas.ToListAsync();

            // Si no hay películas en la base de datos, mostrar un mensaje o redirigir
            if (!peliculas.Any())
            {
                TempData["ErrorMessage"] = "No hay películas disponibles.";
                return RedirectToAction(nameof(Index)); 
            }

            int selectedPeliculaId;

            if (peliculaId.HasValue)
            {
                // Si se pasa un ID de película, usar ese ID
                selectedPeliculaId = peliculaId.Value;
            }
            else
            {
                // Si no se pasa un ID de película, mostrar la lista de películas
                selectedPeliculaId = 0; // Indicamos que no hay una película seleccionada
            }

            // Obtener la película seleccionada si se pasa un ID
            var peliculaSeleccionada = selectedPeliculaId > 0
                ? await _context.Peliculas.FirstOrDefaultAsync(p => p.Id == selectedPeliculaId)
                : null;

            // Si la película seleccionada no existe, redirigir
            if (peliculaSeleccionada == null && selectedPeliculaId > 0)
            {
                TempData["ErrorMessage"] = "Película no encontrada. Por favor, selecciona una película válida.";
                return RedirectToAction(nameof(Index));
            }

            // Obtener los puntos del usuario logueado
            var userId = HttpContext.Session.GetInt32("IDUsuario");
            if (userId != null)
            {
                var usuario = await _context.NuevoUsuario.FirstOrDefaultAsync(u => u.Id == userId.Value);
                if (usuario != null)
                {
                    ViewBag.PuntosUsuario = usuario.Puntos; // Pasar los puntos al ViewBag
                }
            }

            // Cargar las películas en el ViewBag para la lista desplegable (solo si no se seleccionó una película)
            ViewBag.Peliculas = new SelectList(peliculas, "Id", "Titulo", peliculaSeleccionada?.Id);

            if (peliculaSeleccionada != null)
            {
                // Establecer las fechas en el ViewBag según la película seleccionada, si se seleccionó una
                ViewBag.Fechas = selectedPeliculaId > 0
                    ? new SelectList(new List<DateTime> { peliculaSeleccionada.Fecha }, peliculaSeleccionada.Fecha)
                    : new SelectList(Enumerable.Empty<DateTime>());
            }

            return View();
        }

        // POST: Ventas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdPelicula,Fecha,CantButacas,Total,Pelicula,Promocion")] Venta venta)
        {

            // Aseguramos que el navbar esté oculto si estamos en la acción de creación
            ViewData["HideNavbar"] = true;

            // Establecer en TempData que el usuario ha iniciado sesión
            TempData["IsUserLoggedIn"] = true;


            // Validar que la película seleccionada existe
            var pelicula = await _context.Peliculas.FirstOrDefaultAsync(p => p.Id == venta.IdPelicula);

            if (pelicula == null)
            {
                ModelState.AddModelError("IdPelicula", "La película seleccionada no existe.");
                ViewBag.Peliculas = new SelectList(await _context.Peliculas.ToListAsync(), "Id", "Titulo");
                ViewBag.Fechas = new SelectList(Enumerable.Empty<DateTime>());
                return View(venta);
            }

            if (venta.CantButacas < 0)
            {
                ModelState.AddModelError("CantButacas", "La cantidad de butacas no puede ser negativa.");
                ViewBag.Peliculas = new SelectList(await _context.Peliculas.ToListAsync(), "Id", "Titulo");
                ViewBag.Fechas = new SelectList(new List<DateTime> { pelicula.Fecha }, pelicula.Fecha);
                return View(venta);
            }

            if (venta.CantButacas > pelicula.CantButacas)
            {
                ModelState.AddModelError("CantButacas", $"No hay suficientes butacas disponibles. Solo quedan {pelicula.CantButacas} butacas.");
                ViewBag.Peliculas = new SelectList(await _context.Peliculas.ToListAsync(), "Id", "Titulo");
                ViewBag.Fechas = new SelectList(new List<DateTime> { pelicula.Fecha }, pelicula.Fecha);
                return View(venta);
            }

            // Asignar la película y la fecha a la propiedad de la venta
            venta.IdPelicula = pelicula.Id;
            venta.Fecha = pelicula.Fecha;

            // Calcular el total basado en la película seleccionada
            if (venta.Promocion)
            {
                // Si se aplica la promoción 2x1, el total es la mitad
                venta.Total = (pelicula.Precio * venta.CantButacas) / 2;
            }
            else
            {
                // Si no se aplica la promoción, el total es el precio completo
                venta.Total = pelicula.Precio * venta.CantButacas;
            }

            if (ModelState.IsValid)
            {
                // Guardar la venta y actualizar la película
                var userId = HttpContext.Session.GetInt32("IDUsuario");
                if (userId == null)
                {
                    ModelState.AddModelError("", "Debe iniciar sesión para realizar una venta.");
                    return View(venta);
                }

                var usuario = await _context.NuevoUsuario.FirstOrDefaultAsync(u => u.Id == userId);
                if (usuario != null)
                {
                    if (!venta.Promocion)
                    {
                        usuario.Puntos += 200;
                        _context.Update(usuario);
                    }
                    else
                    {
                        usuario.Puntos -= 1000;
                        _context.Update(usuario);
                    }
                }

                venta.IDUsuario = userId.Value;
                pelicula.CantButacas -= venta.CantButacas;
                _context.Update(pelicula);
                _context.Add(venta);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Details), new { id = venta.Id });

            }

            // Si hay un error, recargar las listas para la vista
            ViewBag.Peliculas = new SelectList(await _context.Peliculas.ToListAsync(), "Id", "Titulo");
            ViewBag.Fechas = new SelectList(new List<DateTime> { pelicula.Fecha }, pelicula.Fecha);
            return View(venta);
        }

        [HttpGet]
        public async Task<IActionResult> GetFechasByPelicula(int id)
        {
            var pelicula = await _context.Peliculas.FirstOrDefaultAsync(p => p.Id == id);

            if (pelicula == null)
            {
                return Json(new List<DateTime>());
            }

            return Json(new List<DateTime> { pelicula.Fecha });
        }

        [HttpGet]
        public async Task<IActionResult> GetPrecioByPelicula(int id)
        {
            var pelicula = await _context.Peliculas.FirstOrDefaultAsync(p => p.Id == id);

            if (pelicula == null)
            {
                return Json(0); 
            }

            return Json(pelicula.Precio);
        }

        // GET: Ventas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas.FindAsync(id);
            if (venta == null)
            {
                return NotFound();
            }
            return View(venta);
        }

        // POST: Ventas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdPelicula,Fecha,CantButacas,Total")] Venta venta)
        {
            if (id != venta.Id)

WebApplication-MVC-2024C2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var peliculas = ViewBag.Cartelera as List<WebApplication_MVC_2024C2.Models.Pelicula>;
}



<body class="text-center">
    <div class="titulo-cartelera">

    <h1>PÁGINA DE INICIO</h1>
    <h3>Cartelera de Películas</h3>
    
    </div>

    @if (peliculas != null && peliculas.Any())
    {
        <div class="row">
            @{
                int i = 0;
            }
            @foreach (var pelicula in peliculas)

            {
                <div class="col-md-4">
                    <div class="card card-translucent mb-4 box-shadow">
                        <div class="card-body">

                            @if(i == 0 || i == 1) {
                            <img src="https://www.ecartelera.com/carteles/4500/4578/001_m.jpg"><img/>
                                }else if (i == 2 || i == 3){
                                    <img src="https://xl.movieposterdb.com/10_05/2004/316654/xl_316654_8c68e077.jpg"><img/>
                                    } else
                                        {
                                    <img src="https://www.sonypictures.com.ar/sites/argentina/files/tittle-page/thumbnails/255526_Spiderman3__2007_1400x2100_MEX.jpg"><img/>
                                    }

                            <h5 class="card-title">@pelicula.Titulo</h5>
                            <p class="card-text"><strong>Descripción:</strong> @pelicula.Descripcion</p>
                            <p class="card-text"><strong>Clasificación:</strong> @pelicula.Clasificacion</p>
                            <p class="card-text"><strong>Número de Sala:</strong> @pelicula.NroDeSala</p>
                            <p class="card-text"><strong>Fecha:</strong> @pelicula.Fecha.ToString("dd/MM/yyyy HH:mm")</p>
                            <p class="card-text"><strong>Precio:</strong> $@pelicula.Precio</p>
                            <p class="card-text"><strong>Cantidad de Butacas:</strong> @pelicula.CantButacas</p>                           
                           
                            <!-- Formulario para enviar el Id de la película seleccionada -->
                            <form asp-controller="Ventas" asp-action="RedirectToCreate" method="post">
                                <!-- Campo oculto para enviar el Id de la película -->
                                <input type="hidden" name="peliculaId" value="@pelicula.Id" />
                                <button class="btn btn-primary btn-block" type="submit">Reservar</button>
                            </form>
                        </div>
                    </div>
                </div>

                    i++;
            }
           
        </div>
    }

    else
    {
        <p>No hay películas disponibles en este momento.</p>
    }

</body>